### ISSUE TITLE
TO DO

### ISSUE THREAD

**Issue by Plajer** [TomTheCreator/Village_Defense_2.0#14]
Things to do for next pull request:

- [x] Decapitalise package names
- [ ] Create files: signModification.yml, STATS.yml, SpecialItems.yml and Kits.yml from plugin jar (instead of that weird create file method from gameapi)
- [x] Create UpdateChecker class
- [x] Make plugin prefix (from ChatManager) configurable in language.yml (to do in LanguageMigrator class)
- [x] Add plugin prefixes for rest of messages that need them
- [x] *Make MessageHandler_v1x_xx_Rx classes reflection based (and merge them into 1 class)
- [x] Remove onKick listener from onQuit class (@TomTheCreator quit event is called after kick https://www.spigotmc.org/threads/is-playerquitevent-called-after-playerkickevent.267729/)
- [x] Rename onSpectate listeners in onSpectate class
- [x] Change lines 217-221 in Events class (useless)
- [ ] Make translatable Spawn Wolf item (Events class)
- [x] Remove getLabel() checking from ChestCommands class (use getName() instead)
- [x] Remove is1x_xx_Rx from VillageDefense class (GameAPI class have this methods) + change methods from GameAPI class to return getVersion()... instead of if (getVersion()...) return true; return false;

**Comment by VerschuerenTom** [comment]
DO NOT capitalize package names. Why? ->
https://stackoverflow.com/questions/12534302/why-should-java-package-name-be-lowercase

**Comment by Plajer** [comment]
ok, changed :1st_place_medal:

**Comment by Plajer** [comment]
Rest of things will be added in the future releases.
