### ISSUE TITLE
Very slow zombies [Not sure if this issue continue happening]

### ISSUE THREAD

**Issue by altrisi** [TomTheCreator/Village_Defense_2.0#28]
Since (if I'm not wrong) the pathfinding update, the zombies and villagers in the arena are extremely slow.
Also, I can't understand why the update says 
>Zombies pathfinding was very bad since 1.8 or 1.9 to find villagers inside houses.

In my server ALL the zombies were going to one of the only two doors in the map to try to kill the villagers...

I say "Not sure if this issue continue happening" in the title because I haven't been able to use the plugin since the "LanguageMitigation failed" update because the error reported in issue #27 (update between last and "LanguageMitigation failed" not tested).

No error log available

## Plugin version: _Two different versions tested_

**Comment by Plajer** [comment]
Thanks for reporting that! Someone already reported me that problem but i didn't investigate it yet.
@TomTheCreator will check the problem soon.

**Comment by Plajer** [comment]
btw if you can use 1.12 please do that for now because it works well

**Comment by VerschuerenTom** [comment]
You are aware of the zombie speed config option in the configuration? Didn't change anything in the 1.8.8 pathfinding except for adding that option. It might be that you have to adjust this number to make the zombies run faster. Nonetheless, i'll look into this

**Comment by altrisi** [comment]
In response to Plajer:
I would like to use it, but my computer's graphic card don't support 1.9+ and most of my players are using 1.8.x because similar reasons (performance and combat).

**Comment by altrisi** [comment]
In response to TomTheCreator:
No, I was not aware of that configuration. But as I can remember, the villagers were also very slow.

**Comment by VerschuerenTom** [comment]
Oh okey. Then I might have messed on accident with the 1.8.8 files. Thanks, will fix it.

**Comment by VerschuerenTom** [comment]
Expecting to fix this either 30/11 or 2/12. Just to give you an estimate @altrisi on when this should be fixed.

**Comment by VerschuerenTom** [comment]
@altrisi Zombie speed was set to 0.4, I don't know why anymore though. For 1.8.8, just change the ZOMBIE SPEED property in the config.yml to a higer number. (I recommend between 1.2-1.4) The higher the faster, and the more difficult of course.

Although there was an issue in 1.12 with the zombie speed which I just fixed. Thanks for pointing this out. 

I tested it on my server both on 1.12 and 1.8.8 and it worked on my server. Although if this issue persists on your server, please tell me.
